In [2]:
pip install pymongo

Collecting pymongo
  Downloading pymongo-4.13.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (22 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.7.0-py3-none-any.whl.metadata (5.8 kB)
Downloading pymongo-4.13.2-cp312-cp312-macosx_11_0_arm64.whl (911 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 911.7/911.7 kB 12.9 MB/s eta 0:00:00
Downloading dnspython-2.7.0-py3-none-any.whl (313 kB)
Installing collected packages: dnspython, pymongo
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pymongo]m1/2 [pymongo]
Successfully installed dnspython-2.7.0 pymongo-4.13.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from pymongo import MongoClient

In [40]:
# CSV 로드
csv_path = "User_1000.csv"
df = pd.read_csv(csv_path)
df

,ID,예민함정도,의견수용,말수,시간약속,리더십,체력,청결민감도,여행일정강도,국내or해외,...,싫어하는기후,여행목적,숙소유형,기상시간,여행예산,Summary,Profile,Rec_People,Rec_Travel,summary
0,1,보통,매우 수용적,많다,자주 늦음,따르는 편,4,꽤 민감,매우 여유있게,해외,...,"더움,추움,건조함","액티비티,기록,미식","게스트하우스,펜션,4-5성급호텔",오전 9-10시,200-300만원,NaN,"이 사용자는 세계일주 지역을 선호하고, 건조함 기후를 피하고 싶어해요. 여행 목적은...",NaN,NaN,저는 여행 중에 너무 더운 날씨나 추운 날씨로 인해 불편함을 겪었던 경험이 최악으로...
1,2,둔감,다소 완고,매우 적다,매우 정확,따르는 편,5,둔감,꽤 여유있게,해외,...,"더움,추움,상관없음","공연&경기관람,문화&역사체험,기록","3성이하 호텔,4-5성급호텔,민박",오전 9-10시,200-300만원,NaN,"이 사용자는 미국 지역을 선호하고, 추움 기후를 피하고 싶어해요. 여행 목적은 문화...",NaN,NaN,저는 정해진 계획에 따라 여유롭게 미국과 일본을 여행하며 공연과 경기를 관람하고 다...
2,3,보통,매우 수용적,많다,자주 늦음,무조건 리드,5,꽤 민감,보통,국내,...,"상관없음,습함,건조함","도전과성장,미식,자연감상","4-5성급호텔,콘도,3성이하 호텔",오전 10시 이후,400만원 이상,NaN,"이 사용자는 미국 지역을 선호하고, 상관없음 기후를 피하고 싶어해요. 여행 목적은 ...",NaN,NaN,"저는 여행 중 계획이 틀어지는 것보다 청결하지 못한 환경에서의 경험이 최악이었고, ..."
3,4,매우 둔감,다소 완고,적다,매우 정확,보통,3,꽤 민감,매우 빡빡하게,해외,...,"추움,상관없음,건조함","사람&관계,기록,도전과성장","상관없음,4-5성급호텔,콘도",오전 8-9시,100만원 이하,NaN,"이 사용자는 세계일주 지역을 선호하고, 추움 기후를 피하고 싶어해요. 여행 목적은 ...",NaN,NaN,저는 여행 중 예기치 않게 추운 날씨를 만나는 것을 최악의 경험으로 꼽습니다. 그래...
4,5,보통,매우 수용적,적다,종종 늦음,무조건 따름,2,꽤 민감,꽤 여유있게,해외,...,"건조함,추움,쌀쌀함","자연감상,문화&역사체험,도전과성장","에어비엔비,상관없음,콘도",오전 8-9시,100만원 이하,NaN,"이 사용자는 유럽 지역을 선호하고, 추움 기후를 피하고 싶어해요. 여행 목적은 도전...",NaN,NaN,저는 여행 중 체력이 다소 부족해서 무리한 일정이 최악의 경험으로 남은 적이 있습니...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,매우 둔감,매우 완고,많다,보통,따르는 편,2,둔감,매우 여유있게,해외,...,"쌀쌀함,상관없음,추움","쇼핑,문화&역사체험,휴식","민박,게스트하우스,에어비엔비",오전 8-9시,100만원 이하,NaN,"이 사용자는 동남아 지역을 선호하고, 추움 기후를 피하고 싶어해요. 여행 목적은 휴...",NaN,NaN,여행 중 최악의 경험은 치열한 일정으로 인해 충분히 쉬지 못하는 상황일 것 같아요....
996,997,꽤 민감,매우 완고,매우 적다,꽤 정확,따르는 편,4,매우 둔감,매우 빡빡하게,해외,...,"습함,쌀쌀함,더움","도전과성장,쇼핑,미식","콘도,3성이하 호텔,에어비엔비",오전 8-9시,300-400만원,NaN,"이 사용자는 동남아 지역을 선호하고, 습함 기후를 피하고 싶어해요. 여행 목적은 쇼...",NaN,NaN,"저는 예전에 여행 중 습한 기후 때문에 불쾌한 경험을 한 적이 있어서, 이번 여행에..."
997,998,매우 민감,매우 수용적,보통,자주 늦음,따르는 편,1,매우 둔감,보통,해외,...,"더움,추움,건조함","자연감상,미식,휴식","콘도,3성이하 호텔,4-5성급호텔",오전 8-9시,400만원 이상,NaN,"이 사용자는 국내 지역을 선호하고, 추움 기후를 피하고 싶어해요. 여행 목적은 자연...",NaN,NaN,저는 여행 중 최악의 경험으로 예기치 않게 추운 기후를 만났던 것을 꼽을 수 있어요...
998,999,꽤 민감,다소 완고,많다,자주 늦음,무조건 리드,5,매우 둔감,보통,해외,...,"습함,추움,상관없음","문화&역사체험,공연&경기관람,쇼핑","4-5성급호텔,게스트하우스,3성이하 호텔",오전 10시 이후,400만원 이상,NaN,"이 사용자는 세계일주 지역을 선호하고, 추움 기후를 피하고 싶어해요. 여행 목적은 ...",NaN,NaN,여행 중 최악의 경험으로는 약속에 늦어서 중요한 공연이나 행사에 참석하지 못했던 경...
999,1000,매우 민감,다소 완고,적다,보통,리드하는편,4,매우 둔감,보통,해외,...,"쌀쌀함,상관없음,추움","공연&경기관람,휴식,액티비티","4-5성급호텔,게스트하우스,펜션",오전 8-9시,200-300만원,NaN,"이 사용자는 세계일주 지역을 선호하고, 상관없음 기후를 피하고 싶어해요. 여행 목적...",NaN,NaN,여행 중 최악의 경험은 예상치 못한 쌀쌀한 날씨와 계획에 차질이 발생했을 때입니다....

In [41]:
# MongoDB 연결
client = MongoClient("mongodb+srv://sjy21ys:cjdthdtla12!@cluster0.ozrm81h.mongodb.net/")
db = client["travel_recsys"]
db

Database(MongoClient(host=['ac-kfnvbjp-shard-00-00.ozrm81h.mongodb.net:27017', 'ac-kfnvbjp-shard-00-01.ozrm81h.mongodb.net:27017', 'ac-kfnvbjp-shard-00-02.ozrm81h.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', replicaset='atlas-5ttltc-shard-0', tls=True), 'travel_recsys')

In [52]:
col_features = db["user_features"]
col_profile = db["user_profile"]
col_summary = db["user_summary"]
col_recs = db["user_recs"]
col_travels = db["travel_info"]
col_travels_url = db["travel_url"]

In [51]:
#col_features.delete_many({})
#col_profile.delete_many({})
#col_summary.delete_many({})
col_travels.delete_many({})

DeleteResult({'n': 160, 'electionId': ObjectId('7fffffff000000000000008d'), 'opTime': {'ts': Timestamp(1754964602, 29), 't': 141}, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1754964602, 29), 'signature': {'hash': b'\x8f\x01fT\x9e\x16F\xec\x89\xd4p\x05\nS\x0f4-r/\xdb', 'keyId': 7475774711973019655}}, 'operationTime': Timestamp(1754964602, 29)}, acknowledged=True)

In [44]:
# final_travel CSV 로드
travel_csv_path = "final_travel.csv"
travel_df = pd.read_csv(travel_csv_path)
travel_df

,product_code,title,description,hashtags,features,price,url
0,AAP202250902TWA,방콕/파타야 5일 #첫여행추천 #5성호텔 #니모섬스노클링 #파타야쇼 #핫플레스토랑 ...,"방콕&파타야를 처음 방문하시거나 왕궁, 니모섬 등의 핵심관광지를 제대로 즐기고 싶은...",#관광+자유#관광 #관광 #신비로운니모섬#아름다운방콕#여유로운휴식#방콕파타야여행#니...,"3박 5일, LCC, 쇼핑없음, 단체여행, 가이드경비없음, 선택관광있음","749,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...
1,AAP200250906TWL,[출발확정][타임세일] 방콕/파타야 5일 #가볍게떠나는여행#무앙보란#농눅빌리지#산호...,※알찬 가격으로 방콕/파타야 핵심 관광지를 모두 체험하는 일정입니다.,#관광 #관광 #태국의문화탐방#설레는여행#황홀한바다#방콕파타야여행#무앙보란관광#산호...,"3박 5일, LCC, 쇼핑 3회, 단체여행, 가이드경비 USD 50, 선택관광있음","249,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...
2,ACP200250901OZ1,치앙마이/치앙라이 5일#가성비추천 #3色사원 #4성급호텔#핵심일정#코끼리 먹이주기 체험,합리적인 가격으로 태국 치앙마이 및 치앙라이 지역의 핵심일정을 즐길 수 있는 상품입니다.,#지속가능한 여행 #관광 #아름다운태국의풍경#여유로운여행시간#설레는가이드미팅#치앙마...,"3박 5일, 국적기, 쇼핑 3회, 단체여행, 가이드경비 USD 50, 선택관광있음","499,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...
3,APP2302509017CM,[스마트 초이스] 보홀 5일 #헤난타왈라 #전신마사지 #다이빙강습 #알로나비치 #보...,"온전한 대자연의 땅, 나무, 바다. 이토록 뻔한 자연이 주는 매일매일의 참신함. 나...",#휴양+레저 #관광 #여유로운해변일출#설레는여행추억#편안한휴식시간#필리핀여행#보홀체...,"3박 5일, LCC, 쇼핑 2회, 단체여행, 자유일정포함, 가이드경비 USD 50,...","459,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...
4,APP2382509017CE,보홀 5일 #라메디 #신규오픈 #다이빙강습 #알로나비치 #보홀시티투어 #특식2회,"온전한 대자연의 땅, 나무, 바다. 이토록 뻔한 자연이 주는 매일매일의 참신함. 나...",#휴양+레저 #관광 #여유로운여행#편안한물놀이#감탄을자아내는해변#보홀여행#필리핀체험...,"3박 5일, LCC, 쇼핑 2회, 단체여행, 자유일정포함, 가이드경비 USD 50,...","199,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...
...,...,...,...,...,...,...,...
75,PAP105250906OZA,[스마트 초이스] 시드니/멜버른 7일 #그레이트오션로드 #멜버른핵심투어 #오페라하우...,"★호주여행 이거 하나면 되요!★유럽풍의 멜버른, 오페라하우스가 있는 시드니까지 !호...",#관광 #관광 #설레는호주여행#자연속힐링#고풍스러운멜버른#멜버른핵심투어#그레이트오션...,"5박 7일, 국적기, 쇼핑 2회, 단체여행, 가이드경비 USD 70, 선택관광있음","3,169,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...
76,PAG101250904JQA,[다색골프] 브리스베인/골드코스트 6일#다색골프 # 18홀X3회# 로얄파인즈 외 2...,해당상품은 쇼핑센터에 방문하지 않습니다.,#골프#다색골프 #관광 #여유로운골프여행#설레는호주탐방#잔잔한바다임장#골드코스트골프...,"5박 6일, 외국항공, 쇼핑없음, 단체여행, 가이드경비없음, 선택관광있음","4,439,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...
77,PNP101250907KE1,♥출발확정♥[타임세일][좌석확보] 뉴질랜드 남북섬 핵심일주 9일 #베스트셀러 #밀포...,장엄한 뉴질랜드의 대자연을 마주하다. 뉴질랜드 인기 도시 총집합 ★퀸스타운. 오클랜...,#관광 #관광 #경이로운자연경관#설레는모험여행#평화로운숲속산책#뉴질랜드여행#퀸스타운...,"7박 9일, 국적기, 쇼핑 4회, 단체여행, 가이드경비 USD 90, 선택관광있음","3,199,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...
78,PNZ155250901KE1,뉴질랜드 남/북섬 9일 #남섬 아주르 롯지/북섬 후카 롯지 #힐링 #자연 #온천 #...,남섬 퀸스타운에 위치한 아주르 롯지는 언덕 꼭대기에 위치해 있어 아름다운 호수를 바...,#힐링휴양 #관광 #대자연속휴식#설렘가득여정#멋진풍경감상#노쇼핑여행#안심여행#뉴질랜...,"7박 9일, 국적기, 쇼핑없음, 우리끼리, 자유일정포함, 가이드경비없음, 선택관광없음","21,000,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...
79,PNZ135250901KE1,뉴질랜드 남/북섬 11일 #와이헤케 섬 2박 #델라모어 롯지 #로토루아 #경비행기 ...,"뉴질랜드 사람들이 사랑하는 섬 중에서는 가장 유명한 곳, 와이헤케 섬에서의 하룻밤!",#관광#힐링휴양 #관광 #설레는해외여행#아름다운자연속에서#광활한신비함#노쇼핑여행#뉴...,"9박 11일, 국적기, 쇼핑없음, 우리끼리, 가이드경비없음, 선택관광없음","20,500,000",https://hope.hanatour.com/trp/pkg/CHPC0PKG0200...

In [39]:

for _, row in df.iterrows():
    user_id = int(row["ID"])
    
    feature_cols = [col for col in df.columns if col not in ["ID", "Profile", "Summary", "Rec_People", "Rec_Travel"]]
    features_dict = {col: row[col] for col in feature_cols}
    
    col_features.insert_one({
        "ID": user_id,
        "Features": features_dict
    })
    
    summary_value = row['Summary'] if 'Summary' in df.columns else ""

    col_summary.insert_one({
        "ID": user_id,
        "Summary": summary_value
    })

    profile_value = row["Profile"] if "Profile" in df.columns else ""

    col_profile.insert_one({
        "ID": user_id,
        "Profile": profile_value
    })

    recs_cols = [cor for cor in df.columns if cor.startswith("Rec_")]
    recs_dict = {col: row[col] for col in recs_cols}

    col_recs.insert_one({
        "ID": user_id,
        "Recs": recs_dict
    })

In [48]:
travel_df.columns

Index(['product_code', 'title', 'description', 'hashtags', 'features', 'price',
       'url'],
      dtype='object')

In [53]:
# travel_df를 MongoDB에 삽입
# ['product_code', 'title', 'description', 'hashtags', 'features', 'price'] 와 ['product_code', 'url'] 따로 DB에 저장
for _, row in travel_df.iterrows():
    travel_info = {
        "product_code": row["product_code"],
        "title": row["title"],
        "description": row["description"],
        "hashtags": row["hashtags"].split(",") if pd.notna(row["hashtags"]) else [],
        "features": row["features"].split(",") if pd.notna(row["features"]) else [],
        "price": row["price"] if pd.notna(row["price"]) else []
    }
    
    col_travels.insert_one(travel_info)

for _, row in travel_df.iterrows():
    travel_url = {
        "product_code": row["product_code"],
        "url": row["url"]
    }
    
    col_travels_url.insert_one(travel_url)

In [31]:
client.close()